SimplyRegister/Models/Event.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace SimplyRegister.Models
{
    public class Event
    {
        public int eventId { get; set; }
        [Display(Name = "Event Name")]
        public string eventName { get; set; }
        [Display(Name = "Event Date")]
        public DateTime eventDate { get; set; }
        [Display(Name = "Event Type")]
        public string eventType { get; set; }//Corporate, Training, CLC, other
        [Display(Name = "Corporate Price")]
        public double corporatePrice { get; set; }
        [Display(Name = "Associate Price")]
        public double assocaitePrice { get; set; }
        [Display(Name = "CBA Price")]
        public double cbaPrice { get; set; }
        [Display(Name = "IAP Price")]
        public double iapPrice { get; set; }
        [Display(Name = "Non-Member Price")]
        public double nonMemberPrice { get; set; }

        public List<Customer> Registration { get; set; }


        public virtual ICollection<Registration> Registrations { get; set; }


    }
}

SimplyRegister/Controllers/EventsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SimplyRegister.Models;
using Microsoft.AspNet.Identity;

namespace SimplyRegister.Controllers
{
    public class EventsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        

        // GET: Events
        public ActionResult Index( )
        {
            return View(db.Events.ToList());
        }

        // GET: Events/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Event @event = db.Events.Find(id);
            if (@event == null)
            {
                return HttpNotFound();
            }
            return View(@event);
        }

        // GET: Events/Create
        public ActionResult Create()
        {
            Event @event = new Event();
            return View(@event);
        }

        // POST: Events/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "eventId,eventName,eventDate,eventType")] Event @event)
        {
            if (ModelState.IsValid)
            {
                db.Events.Add(@event);
                db.SaveChanges();
                if (@event.eventType == "Corporate")
                {
                    return RedirectToAction("SetCorporateEventPrices", @event);
                }
                else if (@event.eventType == "Training")
                {
                    return RedirectToAction("SetTrainingEventPrices", @event);
                }
                
            }

            return View(@event);
        }

        // GET: Events/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Event @event = db.Events.Find(id);
            if (@event == null)
            {
                return HttpNotFound();
            }
            return View(@event);
        }

        // POST: Events/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "eventId,eventName,eventDate,eventType, corporatePrice, assocaitePrice, cbaPrice, iapPrice, nonMemberPrice ")] Event @event)
        {
            if (ModelState.IsValid)
            {
                db.Entry(@event).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(@event);
        }

        // GET: Events/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Event @event = db.Events.Find(id);
            if (@event == null)
            {
                return HttpNotFound();
            }
            return View(@event);
        }

        // POST: Events/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Event @event = db.Events.Find(id);
            db.Events.Remove(@event);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }


        //GET
        public ActionResult SetCorporateEventPrices(Event @event, bool overloadFiller = false)
        {
            return View(@event);
        }

        //POST
        [HttpPost]
        public ActionResult SetCorporateEventPrices([Bind(Include = "eventId, eventName, eventDate, eventType, corporatePrice, assocaitePrice, cbaPrice, iapPrice, nonMemberPrice")] Event @event)
        {
            
            if (ModelState.IsValid)
            {
                db.Entry(@event).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("AdminEventIndex");
            }
            return View(@event);
            
        }


        //GET
        public ActionResult SetTrainingEventPrices(Event @event, bool overloadFiller = false)
        {
            return View(@event);
        }


        //POST
        [HttpPost]
        public ActionResult SetTrainingEventPrices([Bind(Include = "eventId, eventName, eventDate, eventType, corporatePrice, assocaitePrice, cbaPrice, iapPrice, nonMemberPrice")] Event @event)
        {
            if (ModelState.IsValid)
            {
                db.Entry(@event).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(@event);
        }

        public ActionResult RegisterCustomer(int id)
        {

            var Id = User.Identity.GetUserId();
            var customer = db.Customers.FirstOrDefault(c => c.userId == Id);
            var company = db.Companies.FirstOrDefault(c => c.companyId == customer.customerCompany);

            var @event = db.Events.SingleOrDefault(m => m.eventId == id);
            //var user = ApplicationUserManager.//FindById(User.Identity.GetUserId())
            var user = User.Identity.GetUserId();
            if(@event.eventType == "Corporate" && company.companyMembershipLevel != "Corporate" && company.companyMembershipLevel != "Associate")
            {
                return View("RegisterCustomerNonMember");
            }
            else
            {
                return View(@event);
                
            }
            
        }

        
        public ActionResult RegisterCustomerTwo(int customerId,int eventId, double amountBilled)
        {
            Registration reg = new Registration();
            reg.customerId = customerId;
            reg.eventId = eventId;
            reg.amountBilled = amountBilled;

            db.Registrations.Add(reg);
            db.SaveChanges();
            return RedirectToAction("MakePayment", "Customers", reg);
        }

        [HttpPost]
        public ActionResult AddRegistration(Registration reg)
        {
            db.Registrations.Add(reg);
            db.SaveChanges();
            return View("MakePayment", "Customers", reg);
        }

        public ActionResult AdminEventIndex()
        {
            
            return View(db.Events.ToList());
        }




    }
}

SimplyRegister/Views/Events/AddRegistration.cshtml

@{
    ViewBag.Title = "AddRegistration";
}

<h2>AddRegistration</h2>


SimplyRegister/Views/Events/AdminEventIndex.cshtml
@model IEnumerable<SimplyRegister.Models.Event>

@{
    ViewBag.Title = "Index";
}

<h2>List of Events</h2>
<p>@Html.ActionLink("Create New", "Create")</p>


<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.eventName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.eventDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.eventType)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.corporatePrice)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.assocaitePrice)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.cbaPrice)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.iapPrice)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.nonMemberPrice)
        </th>
        <th></th>
    </tr>
@foreach (var item in Model)
{
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.eventName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.eventDate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.eventType)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.corporatePrice)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.assocaitePrice)
        </td>
        <td>
            @if (item.cbaPrice == 0)
            {
                @Html.DisplayName("Members Only")
            }
            else
            {
                @Html.DisplayFor(modelItem => item.cbaPrice)
            }
        </td>
        <td>
            @if (item.iapPrice == 0)
            {
                @Html.DisplayName("Members Only")
            }
            else
            {
                @Html.DisplayFor(modelItem => item.iapPrice)
            }
        </td>
        <td>
            @if (item.nonMemberPrice == 0)
            {
                @Html.DisplayName("Members Only")
            }
            else
            {
                @Html.DisplayFor(modelItem => item.nonMemberPrice)
            }

        </td>
        <td>
        @Html.ActionLink("Edit", "Edit", new { id = item.eventId }) |
        @Html.ActionLink("Details", "Details", new { id = item.eventId }) |
        @Html.ActionLink("Delete", "Delete", new { id = item.eventId })
        </td>
        

</tr>
}

SimplyRegister/Views/Events/Create.cshtml
@model SimplyRegister.Models.Event

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Event</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        

        <div class="form-group">
            @Html.LabelFor(model => model.eventName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.eventName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.eventName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.eventDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.eventDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.eventDate, "", new { @class = "text-danger" })
            </div>
        </div>




        <div class="form-group">
            @Html.LabelFor(model => model.eventType, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(e => e.eventType, new List<SelectListItem>
                { new SelectListItem{Text="Corporate", Value="Corporate"},
                 new SelectListItem{Text="Training", Value="Training"},
                 //new SelectListItem{Text="CLC", Value="CLC"},
                }, "Select Event Type")
                @Html.ValidationMessageFor(model => model.eventType, "", new { @class = "text-danger" })
            </div>
        </div>





            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-default" />
                </div>
            </div>
        </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

SimplyRegister/Views/Events/Delete.cshtml
@model SimplyRegister.Models.Event

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Event</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.eventName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.eventName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.eventDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.eventDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.eventType)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.eventType)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

SimplyRegister/Views/Events/Details.cshtml
@model SimplyRegister.Models.Event

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Event</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.eventName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.eventName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.eventDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.eventDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.eventType)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.eventType)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.eventId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

SimplyRegister/Views/Events/Edit.cshtml
@model SimplyRegister.Models.Event

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Event</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.eventId)

        <div class="form-group">
            @Html.LabelFor(model => model.eventName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.eventName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.eventName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.eventDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.eventDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.eventDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.eventType, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.eventType, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.eventType, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.corporatePrice, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.corporatePrice, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.corporatePrice, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.assocaitePrice, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.assocaitePrice, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.assocaitePrice, "", new { @class = "text-danger" })
            </div>
        </div>


        @if(Model.eventType == "Training")
        {
        <div class="form-group">
            @Html.LabelFor(model => model.iapPrice, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.iapPrice, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.iapPrice, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.cbaPrice, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.cbaPrice, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.cbaPrice, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.nonMemberPrice, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.nonMemberPrice, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.nonMemberPrice, "", new { @class = "text-danger" })
            </div>
        </div>

        }



        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "AdminEventIndex")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

SimplyRegister/Views/Events/Index.cshtml
@model IEnumerable<SimplyRegister.Models.Event>

@{
    ViewBag.Title = "Index";
}

<h2>List of Events</h2>
@*<p>
    @Html.ActionLink("Create New", "Create")
</p>*@
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.eventName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.eventDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.eventType)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.corporatePrice)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.assocaitePrice)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.cbaPrice)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.iapPrice)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.nonMemberPrice)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.eventName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.eventDate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.eventType)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.corporatePrice)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.assocaitePrice)
        </td>
        <td>
            @if (item.cbaPrice == 0)
            {
                @Html.DisplayName("Members Only")
            }
            else {
            @Html.DisplayFor(modelItem => item.cbaPrice)
            }
        </td>
        <td>
            @if (item.iapPrice == 0)
            {
                @Html.DisplayName("Members Only")
            }
            else
            {
                @Html.DisplayFor(modelItem => item.iapPrice)
            }
        </td>
        <td>
            @if (item.nonMemberPrice == 0)
            {
                @Html.DisplayName("Members Only")
            }
            else
            { 
                @Html.DisplayFor(modelItem => item.nonMemberPrice)
            }
         </td>

        @*<td>
            <p><a class="btn btn-default" href="..\Customers\EventRegister">Register &raquo;</a></p>
        </td>*@
       
        
        
        
         <td>
            @Html.ActionLink("Register", "RegisterCustomer","Events", new { id=item.eventId }, null) 


             @*@Html.ActionLink("Edit", "Edit", new { id = item.eventId }) |*@

            @*@Html.ActionLink("Details", "Details", new { id=item.eventId }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.eventId })*@
        </td>
    </tr>
}

</table>

SimplyRegister/Views/Events/RegisterCustomer.cshtml
@model SimplyRegister.Models.Event
@using Microsoft.AspNet.Identity;
@using SimplyRegister.Models;
@{
    ViewBag.Title = Model.eventName;
}

@*<h2>RegisterCustomer</h2>
<h2>@Model.eventName</h2>*@

<div>


    @{
        ApplicationDbContext db = new ApplicationDbContext();
        var Id = User.Identity.GetUserId();
        var customer = db.Customers.FirstOrDefault(c => c.userId == Id);
        var company = db.Companies.FirstOrDefault(c => c.companyId == customer.customerCompany);
        var priceLevel = company.companyMembershipLevel;
        double actualPrice = 0;
        <h2>@customer.firstName, would you like to register for:</h2><br/>
        <h2>@Model.eventName</h2>

        <h2>Your price:</h2>
        if (priceLevel == "Corporate")
        {
            <h2> $@Model.corporatePrice</h2>
            actualPrice = Model.corporatePrice;
        }
        else if (priceLevel == "Associate")
        {
            <h2> $@Model.assocaitePrice</h2>
            actualPrice = Model.assocaitePrice;
        }
        else if (priceLevel == "CBA")
        {
            <h2> $@Model.cbaPrice</h2>
            actualPrice = Model.cbaPrice;
        }
        else if (priceLevel == "IAP")
        {
            <h2> $@Model.iapPrice</h2>
            actualPrice = Model.iapPrice;
        }
        else if (priceLevel == "Non-Member")
        {
            <h2> $@Model.nonMemberPrice</h2>
            actualPrice = Model.nonMemberPrice;
        }
        Registration registration = new Registration();
        registration.customerId = customer.customerId;
        registration.eventId = Model.eventId;
        registration.amountBilled = actualPrice;


       
        
            @Html.ActionLink("Yes, Register & Pay", "RegisterCustomerTwo", new { customerId = customer.customerId, eventId = Model.eventId, amountBilled = actualPrice }, null)
        



        @*<div class="form-group"> 
            @Html.HiddenFor(registration);
            @Html.HiddenFor(m => m.Password)
            @Html.HiddenFor(m => m.ConfirmPassword)
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Register and Make Payment" class="btn btn-default" />
            </div>

        </div>*@



        //var currentUserName = <h2>@User.Identity.Name;</h2>
                @*var currentUserId = <h2>@Model.Users.Where(m => m.UserName == currentUserName).Select(m => m.Id).First();</h2>*@

    @*var user = UserManager.FindById(User.Identity.GetUserId())

    @var priceLevel = customer.company.companyMembershipLevel;
    @if  (priceLevel == "Corporate")
    {
    registration.amountBilled = Model.@event.corporatePrice;
    }
    else if (priceLevel == "Associate")
    {
    registration.amountBilled = @event.assocaitePrice;
    }
    else if (priceLevel == "CBA")
    {
    registration.amountBilled = @event.cbaPrice;
    }
    else if (priceLevel == "IAP")
    {
    registration.amountBilled = @event.iapPrice;
    }
    else if (priceLevel == "Non-Member")
    {
    registration.amountBilled = @event.nonMemberPrice;
    }*@
        }



    
</div>

SimplyRegister/Views/Events/RegisterCustomerNonMember.cshtml

@{
    ViewBag.Title = "RegisterCustomerNonMember";
}

<h2 style="color: red">Sorry, Only Members Can Register For This Event</h2>

@Html.ActionLink("Back To Events List","Index")




SimplyRegister/Views/Events/SetCorporateEventPrices.cshtml
@model SimplyRegister.Models.Event
@{
    ViewBag.Title = "SetCorporateEventPrices";
}

<h2>Set Corporate Event Prices</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
<div class="form-horizontal">

    <div class="form-group">
        @Html.LabelFor(model => model.corporatePrice, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.corporatePrice, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.corporatePrice, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.assocaitePrice, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.assocaitePrice, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.assocaitePrice, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Add Prices" class="btn btn-default" />
        </div>
    </div>

</div>
}

SimplyRegister/Views/Events/SetTrainingEventPrices.cshtml
@model SimplyRegister.Models.Event
@{
    ViewBag.Title = "SetTrainingEventPrices";
}

<h2>SetTrainingEventPrices</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div class="form-horizontal">

        <div class="form-group">
            @Html.LabelFor(model => model.corporatePrice, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.corporatePrice, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.corporatePrice, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.assocaitePrice, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.assocaitePrice, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.assocaitePrice, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.iapPrice, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.iapPrice, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.iapPrice, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.cbaPrice, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.cbaPrice, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.cbaPrice, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.nonMemberPrice, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.nonMemberPrice, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.nonMemberPrice, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Add Prices" class="btn btn-default" />
            </div>
        </div>





    </div>
}